name: tf-app-deploy
env:
  NODE_VERSION: 14.x
  PACKAGE_LOCATION: sample.zip
  TERRAFORM_BASE_PATH: 'ci/infra/terraform/'
  VAR_BASE_PATH: 'ci/infra/terraform/'
  FRUBEPATH: 'whatthefudgeshouldiread'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: action-foobar/whatthefudgeshouldiread
          token: ${{ secrets.SAML_GITHUB_TOKEN }}
          ref: main
          path: ${{ env.FRUBEPATH }}
      - name: Build
        run: |
          cd ${{ env.FRUBEPATH }}
          npm install
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Zip Web App package
        run: 
          zip -r ${{ env.FRUBEPATH }}/${{ env.PACKAGE_LOCATION }} .
          cp ${{ env.FRUBEPATH }}/${{ env.PACKAGE_LOCATION }} .
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact-${{ github.sha }}
          path: |
            ./${{ env.PACKAGE_LOCATION }}
            dist
            version 

  apply-dev-euw-layer3:
    runs-on: ubuntu-latest
    needs: [build]
    name: apply-euw-layer3
    env:
      LAYER_NAME: layer-3  
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact-${{ github.sha }}
      - name: move stuff
        run: |
          cp ${{ env.PACKAGE_LOCATION }} ci/infra/terraform/layer-3/        
      - name: Checkout
        uses: actions/checkout@v2      
      - name: getsecrets
        env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: echo $GOOGLE_APPLICATION_CREDENTIALS >> GOOGLE_APPLICATION_CREDENTIALS.json
      - name: apply
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/GOOGLE_APPLICATION_CREDENTIALS.json
        uses: dflook/terraform-apply@v1.22.1
        with:
          variables: |
            location     = "europe-west"
          auto_approve: true
          path: ${{ env.TERRAFORM_BASE_PATH }}/${{ env.LAYER_NAME }}
#          var_file: ${{ env.VAR_BASE_PATH }}/vars/common.tfvars
          backend_config: bucket=statestore-eu-donefortheday, prefix=layer-3-app-deveuw.tfstate

