name: tf-app-deploy
env:
  TERRAFORM_BASE_PATH: 'ci/infra/terraform/'
  VAR_BASE_PATH: 'ci/infra/terraform/'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  apply-dev-euw-layer3:
    runs-on: ubuntu-latest
    name: apply-euw-layer3
    env:
      LAYER_NAME: layer-3  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: getsecrets
        env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: echo $GOOGLE_APPLICATION_CREDENTIALS >> GOOGLE_APPLICATION_CREDENTIALS.json
      - name: apply
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/GOOGLE_APPLICATION_CREDENTIALS.json
        uses: dflook/terraform-apply@v1.22.1
        with:
          variables: |
            location     = "europe-west"
            app_name     = "notaclue-euw"
          auto_approve: true
          path: ${{ env.TERRAFORM_BASE_PATH }}/${{ env.LAYER_NAME }}
          var_file: ${{ env.VAR_BASE_PATH }}/vars/common.tfvars
          backend_config: bucket=statestore-eu-first, prefix=layer-3-app-deveun.tfstate
          
  apply-dev-eun-layer3:
    runs-on: ubuntu-latest
    name: apply-eun-layer3
    env:
      LAYER_NAME: layer-3  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: getsecrets
        env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: echo $GOOGLE_APPLICATION_CREDENTIALS >> GOOGLE_APPLICATION_CREDENTIALS.json    
      - name: apply
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/GOOGLE_APPLICATION_CREDENTIALS.json
        uses: dflook/terraform-apply@v1.22.1
        with:
          variables: |
            location     = "europe-central2"
            app_name     = "notaclue-eun"
          auto_approve: true
          path: ${{ env.TERRAFORM_BASE_PATH }}/${{ env.LAYER_NAME }}
          var_file: ${{ env.VAR_BASE_PATH }}/vars/common.tfvars
          backend_config: bucket=statestore-eu-first, prefix=layer-3-app-deveuw.tfstate #name interchange for regions (because of lack of common sense from me :D)
          
  # apply-layer4:
  #   # if: ${{ inputs.TRIGGER_EVENT == 'push' }}
  #   needs: apply-layer3
  #   runs-on: ubuntu-latest
  #   name: apply-layer4
  #   env:
  #     LAYER_NAME: layer-4 
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: apply
  #       env:
  #         GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sample-app/nowwilltrymore-c1e2afe68da3.json
  #       uses: dflook/terraform-apply@v1.22.1
  #       with:
  #         auto_approve: true
  #         path: ${{ env.TERRAFORM_BASE_PATH }}/${{ env.LAYER_NAME }}
  #         backend_config: bucket=statestore-eu-first, prefix=layer-4-edge-deveun.tfstate

      
