name: tf-app
env:
  TERRAFORM_BASE_PATH: 'ci/infra/terraform/'

on:
  workflow_dispatch:

jobs:
  app-deploy:
    runs-on: ubuntu-latest
    name: deploy
    env:
      LAYER_NAME: layer-3
      TERRAFORM_PRE_RUN: |
        curl https://dl.google.com/dl/cloudsdk/release/install_google_cloud_sdk.bash | bash
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GCP-login
        run : gcloud auth activate-service-account --key-file=sample-app/nowwilltrymore-c1e2afe68da3.json --project=noideahowitworks
      - name: TF-Apply
        uses: dflook/terraform-apply@v1.22.1
        with:
          auto_approve: true
          path: ${{ env.TERRAFORM_BASE_PATH }}/${{ env.LAYER_NAME }}
          backend_config: bucket=statestore-eu-first" -backend-config="prefix=layer-3-app-deveun.tfstate

      
